#!/bin/bash

cd code

cd cominisatps
rm -f core simp mtl utils
ln -s minisat/core minisat/simp minisat/mtl minisat/utils .
make clean lr
cd ..

cd maxpre
make clean lib
cd ..

rm -rf scipoptsuite-8.1.0

tar zxf scipoptsuite-8.1.0.tgz
cd scipoptsuite-8.1.0

rm -rf build

mkdir build && cd build
cmake -DNO_EXTERNAL_CODE=on -DSOPLEX=on -DTPI=tny -DSHARED=off ..
cmake --build . --config Release --target libscip libsoplex-pic
cd ../..

cd uwrmaxsat

rm -rf build

make distclean     2>/dev/null || true
make config
make r

cp -p build/release/bin/uwrmaxsat ../../bin/
rm -rf build

cd ../..

rm -rf code/scipoptsuite-8.0.0

sudo cp bin/uwrmaxsat /usr/local/bin/uwrmaxsat
sudo chmod +x /usr/local/bin/uwrmaxsat
