# incr.py

import os
import sys
import time
import pandas as pd
from ppdsp_reform_utils import GlobalVariableRegistry, PPDSP_utils
from ppdsp_reform_p1_cplex import PPDSP_MIP
from ppdsp_reform_p1_rc2 import PPDSP_MaxSAT_p1
from ppdsp_reform_p2_rc2 import PPDSP_MaxSAT_p2
from ppdsp_reform_p3_rc2 import PPDSP_MaxSAT_p3
from ppdsp_reform_p4_rc2 import PPDSP_MaxSAT_p4
from ppdsp_reform_p5_rc2 import PPDSP_MaxSAT_p5
from ppdsp_reform_p6_rc2 import PPDSP_MaxSAT_p6

def auto_slice_csvs(tsplib, max_r, max_v, curr_r, curr_v):
	"""
	Automatic Dynamic Slicing: Slice the curr_r / curr_v rows from the Master CSV.
	"""
	# 1. Slice Request
	curr_req_file = f'requestInfo{curr_r}_{tsplib}.csv'
	if not os.path.exists(curr_req_file):
		master_req_file = f'requestInfo{max_r}_{tsplib}.csv'
		if not os.path.exists(master_req_file):
			print(f"  [Fatal] Master request file {master_req_file} missing! Please generate it first.")
			sys.exit(1)
		df_req = pd.read_csv(master_req_file, header=None)
		df_req.head(int(curr_r)).to_csv(curr_req_file, header=False, index=False)
		print(f"  [Auto-Slice] Created {curr_req_file} from Master ({max_r}).")

	# 2. Slice Vehicle
	curr_veh_file = f'vehicleCap{curr_v}_{tsplib}.csv'
	if not os.path.exists(curr_veh_file):
		master_veh_file = f'vehicleCap{max_v}_{tsplib}.csv'
		if not os.path.exists(master_veh_file):
			print(f"  [Fatal] Master vehicle file {master_veh_file} missing! Please generate it first.")
			sys.exit(1)
		df_veh = pd.read_csv(master_veh_file, header=None)
		df_veh.head(int(curr_v)).to_csv(curr_veh_file, header=False, index=False)
		print(f"  [Auto-Slice] Created {curr_veh_file} from Master ({max_v}).")

if __name__ == "__main__":
	# E.g.: python incr.py maxsat p4 burma14 5,2,3 10,2,3 15,3,4
	#       python incr.py mip p1 burma14 7,2,3 10,2,4 13,3,5
	if len(sys.argv) < 5:
		print("Usage: python incr.py <mode> <method> <tsplib> <R_1,V_1,K_1> <R_2,V_2,K_2> ...")
		print("Example: python incr.py mip p1 burma14 7,2,3 8,2,3 9,2,3 10,2,3 11,2,3 12,2,3 13,2,3 13,3,3")
		sys.exit(1)

	mode = sys.argv[1] # mip / maxsat
	method = sys.argv[2] # p1 / p2 / ...
	tsplib = sys.argv[3]
	raw_sequence = sys.argv[4:]
	
	# Analyze the R,V,K sequence for auto-slicing
	sequence = []
	max_r, max_v = 0, 0
	for seq_str in raw_sequence:
		parts = seq_str.split(',')
		if len(parts) != 3:
			print(f"Error: Sequence format must be R,V,K (got {seq_str})")
			sys.exit(1)
		r, v, k = parts[0], parts[1], parts[2]
		sequence.append((r, v, k))
		max_r = max(max_r, int(r))
		max_v = max(max_v, int(v))

	print("="*70)
	print(f">>> MULTI-DIMENSIONAL ROLLING HORIZON ({mode.upper()}) <<<")
	print(f"Instance: {tsplib} | Method: {method}")
	print(f"Master Bounds Required -> Requests: {max_r}, Vehicles: {max_v}")
	print(f"Incremental Sequence (R,V,K): {sequence}")
	print("="*70)

	# ==========================================
	# 1. Initialize the unique global variable registry (the baton)
	# ==========================================
	global_registry = GlobalVariableRegistry()
	previous_assumption_file = None

	# ==========================================
	# Time Bank Manager
	# ==========================================
	TOTAL_TIME_BUDGET = 480.0  # Total time-limit
	num_steps = len(sequence)
	base_time_limit = TOTAL_TIME_BUDGET / num_steps
	accumulated_saved_time = 0.0

	print(f"  [Time Manager] Total Budget: {TOTAL_TIME_BUDGET}s | Steps: {num_steps} | Base Time per Step: {base_time_limit:.2f}s")

	for idx, (curr_r, curr_v, curr_k) in enumerate(sequence):
		print(f"\n[{idx+1}/{len(sequence)}] Building & Solving: R={curr_r}, V={curr_v}, K={curr_k}")

		# Auto-Slice CSVs for the current round
		auto_slice_csvs(tsplib, max_r, max_v, curr_r, curr_v)
		
		# Check k-NN adjacency matrix file existence (k-NN cannot be sliced, must be generated by ins_arg)
		if not os.path.exists(f'adjMatrx{curr_k}_{tsplib}.csv'):
			print(f"  [Fatal] adjMatrx{curr_k}_{tsplib}.csv not found! Please run ins_arg.py to generate it.")
			sys.exit(1)
		
		# ==========================================
		# 2. Instantiate the solver for the current round, injecting the global registry
		# ==========================================
		if mode == "mip":
			solver = PPDSP_MIP(tsplib, curr_r, curr_v, curr_k, increment=global_registry)
			print("  [Info] Generating MIP Formulation...")
			solver.genMipFormular()
			solver.writeLpFile()
			log_file = solver.insName + ".lp.out"
		elif mode == "maxsat":
			if method == "p1":
				solver = PPDSP_MaxSAT_p1(tsplib, curr_r, curr_v, curr_k, increment=global_registry)
			elif method == "p2":
				solver = PPDSP_MaxSAT_p2(tsplib, curr_r, curr_v, curr_k, increment=global_registry)
			elif method == "p3":
				solver = PPDSP_MaxSAT_p3(tsplib, curr_r, curr_v, curr_k, increment=global_registry)
			elif method == "p4":
				solver = PPDSP_MaxSAT_p4(tsplib, curr_r, curr_v, curr_k, increment=global_registry)
			elif method == "p5":
				solver = PPDSP_MaxSAT_p5(tsplib, curr_r, curr_v, curr_k, increment=global_registry)
			elif method == "p6":
				solver = PPDSP_MaxSAT_p6(tsplib, curr_r, curr_v, curr_k, increment=global_registry)
			else:
				print(f"Unknown maxsat method: {method}")
				sys.exit(1)
			print("  [Info] Generating MaxSAT Formulation...")
			solver.genMaxsatFormular()
			log_file = solver.insName + ".wcnf.out"
		else:
			print(f"Mode {mode} not fully supported in this script yet.")
			sys.exit(1)

		# ==========================================
		# 3. Solve the current sub-problem with Dynamic Time Allocation
		# ==========================================
		# Count usable time for this step
		current_time_limit = base_time_limit + accumulated_saved_time
		print(f"  [Time Manager] Base: {base_time_limit:.2f}s | Saved from past: {accumulated_saved_time:.2f}s | Budget for this step: {current_time_limit:.2f}s")
		
		# Record the start time before solving
		start_time = time.time()
		
		# Allocate time for solving the current sub-problem
		solver.solve(time_limit=int(current_time_limit), assumption_file=previous_assumption_file)
		
		# Record the end time after solving, calculate actual elapsed time
		elapsed_time = time.time() - start_time
		
		# Calculate time banking
		if elapsed_time < current_time_limit:
			# Save the unused time for future steps
			accumulated_saved_time = current_time_limit - elapsed_time
			print(f"  [Time Manager] Solved early in {elapsed_time:.2f}s! Banking {accumulated_saved_time:.2f}s for next steps.")
		else:
			# Reset the time bank if we exhausted the budget
			accumulated_saved_time = 0.0
			print(f"  [Time Manager] Time limit exhausted ({elapsed_time:.2f}s used). No time banked.")

		# ==========================================
		# 4. Parse the solver's log to extract the new assumption for the next round
		# ==========================================
		if mode == "mip":
			next_assumption_file = solver.insName + ".lp.asp"
		elif mode == "maxsat":
			next_assumption_file = solver.insName + ".wcnf.asp"
		else:
			print(f"Mode {mode} not fully supported in this script yet.")
			sys.exit(1)
		
		success = PPDSP_utils.parse_and_save_assumption(
			log_file, 
			next_assumption_file, 
			solver.getLastYVarID(), 
			mode
		)
		
		if success:
			previous_assumption_file = next_assumption_file
		else:
			print("  [Error] Stopping incremental sequence due to failure in extracting assumption.")
			break

	print("\n>>> ROLLING HORIZON COMPLETED SUCCESSFULLY <<<")